name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Install python
      run: sudo apt update && sudo apt install -y python3 python3-pip

    - name: Install poetry
      run: sudo pip3 install poetry

    - name: Install poetry requirements
      run: poetry install

    - name: Run pytest
      run: poetry run python -m pytest
